
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10 #\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-active: 20 #\u6700\u5927\u8FDE\u63A5\u6570
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #\u4E0D\u7EDF\u8BA1\u8FD9\u4E9B\u8BF7\u6C42\u6570\u636E
      stat-view-servlet: #\u8BBF\u95EE\u76D1\u63A7\u7F51\u9875\u7684\u767B\u5F55\u7528\u6237\u540D\u548C\u5BC6\u7801
        login-username: druid
        login-password: druid
  jackson: #\u540E\u53F0\u4F20\u7ED9\u524D\u53F0\u7684date\u7C7B\u578B\u8F6C\u4E3A\u6B64\u683C\u5F0F(localdatetime\u4E0D\u53EF\u4EE5)
    date-format: yyyy-MM-dd HH:mm:ss
#    locale: zh_CN   #\u7528\u4E8E\u683C\u5F0F\u5316\u7684\u8BED\u8A00\u73AF\u5883

 #\u914D\u7F6Esql\u6253\u5370\u65E5\u5FD7,\u8BBE\u7F6Exml\u4F4D\u7F6E
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mapper/*.xml

logging:
  level:
    root: WARN
    com:
      zc:
        mybatis_plus_demo:
          mapper: debug


